### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by jde1126** [kubikplugins/pugpress#2]
Fatal error: Uncaught Error: Class 'PugPress' not found in /customers/b/4/9/snazzy.one/httpd.www/three-js/wp-content/plugins/pugpress-1.1.1/pugpress.php:34 Stack trace: #0 /customers/b/4/9/snazzy.one/httpd.www/three-js/wp-admin/includes/plugin.php(2255): include() #1 /customers/b/4/9/snazzy.one/httpd.www/three-js/wp-admin/plugins.php(177): plugin_sandbox_scrape('pugpress-1.1.1/...') #2 {main} thrown in /customers/b/4/9/snazzy.one/httpd.www/three-js/wp-content/plugins/pugpress-1.1.1/pugpress.php on line 34

I am trying to activate the plugin on a subdomain of mine.
https://three-js.snazzy.one/

**Comment by sandrodz** [comment]
Hi,

You need to run `composer install` in the root directory of the plugin.
